#pragma once
#include <M5Cardputer.h>
void expensesOpen();
void expensesQuickOpen();
void drawExpenses();
void handleExpensesInput(Keyboard_Class::KeysState &keys);
bool expensesModalActive();
bool expensesQuickActive();
void cancelExpensesModal();
bool expensesHasSelection();
void expensesNew();
void expensesMoveTomorrow();
void expensesPromptMoveDate();
void expensesEdit();
void expensesDelete();
void expensesToggleSynced();
void expensesUploadSelected();
bool expensesResumePendingUpload();
void expensesCancelPendingUpload();
void expensesShareQr();
void expensesEditDefaultCurrency();
String expensesDefaultCurrency();
