from __future__ import annotations

import json
import re
from pathlib import Path


IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
REQUIRED_CALLBACKS = ("open", "draw", "input", "tick")


def fail(path: Path, message: str) -> None:
    raise RuntimeError(f"{path}: {message}")


def require_identifier(path: Path, value: object, field: str) -> str:
    if not isinstance(value, str) or not IDENTIFIER.match(value):
        fail(path, f"{field} must be a C++ identifier")
    return value


def require_string(path: Path, data: dict, field: str) -> str:
    value = data.get(field)
    if not isinstance(value, str) or not value:
        fail(path, f"{field} must be a non-empty string")
    return value


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def load_manifests(apps_dir: Path) -> list[dict]:
    manifests = []
    for path in sorted(apps_dir.glob("*/app.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            fail(path, f"invalid JSON: {error}")

        app_id = require_identifier(path, data.get("id"), "id")
        persistent_id = data.get("persistent_id")
        if not isinstance(persistent_id, int) or persistent_id < 0 or persistent_id > 255:
            fail(path, "persistent_id must be an integer from 0 to 255")

        if not isinstance(data.get("order", 1000), int):
            fail(path, "order must be an integer")

        includes = data.get("includes", [])
        if not isinstance(includes, list) or not all(isinstance(item, str) and item for item in includes):
            fail(path, "includes must be a list of header paths")

        callbacks = data.get("callbacks")
        if not isinstance(callbacks, dict):
            fail(path, "callbacks must be an object")
        for field in REQUIRED_CALLBACKS:
            require_identifier(path, callbacks.get(field), f"callbacks.{field}")

        help_data = data.get("help")
        if not isinstance(help_data, dict):
            fail(path, "help must be an object")
        require_string(path, help_data, "title")
        require_identifier(path, help_data.get("entries"), "help.entries")
        require_identifier(path, help_data.get("count"), "help.count")

        options = data.get("options")
        if not isinstance(options, dict):
            fail(path, "options must be an object")
        require_identifier(path, options.get("build"), "options.build")
        for field in ("enter_enabled", "show_run_hint"):
            if not isinstance(options.get(field), bool):
                fail(path, f"options.{field} must be true or false")

        quick = data.get("quick_access")
        if quick is not None:
            if not isinstance(quick, dict):
                fail(path, "quick_access must be an object or null")
            key = quick.get("key")
            if not isinstance(key, str) or len(key) != 1 or not key.isascii() or not key.isalnum():
                fail(path, "quick_access.key must be one ASCII letter or digit")
            require_identifier(path, quick.get("open"), "quick_access.open")
            require_identifier(path, quick.get("available"), "quick_access.available")
            require_identifier(path, quick.get("active"), "quick_access.active")
            require_identifier(path, quick.get("close"), "quick_access.close")
            require_identifier(path, quick.get("input"), "quick_access.input")

        require_string(path, data, "name")
        require_string(path, data, "header_tag")
        data["_path"] = path
        manifests.append(data)

    if not manifests:
        fail(apps_dir, "no app.json manifests found")

    ids = [item["id"] for item in manifests]
    if len(ids) != len(set(ids)):
        fail(apps_dir, "app IDs must be unique")

    persistent_ids = [item["persistent_id"] for item in manifests]
    if len(persistent_ids) != len(set(persistent_ids)):
        fail(apps_dir, "persistent_id values must be unique")
    quick_keys = [item["quick_access"]["key"].lower() for item in manifests if item.get("quick_access")]
    if len(quick_keys) != len(set(quick_keys)):
        fail(apps_dir, "quick_access keys must be unique (case-insensitive)")

    return manifests


def generate(project_dir: Path) -> None:
    manifests = load_manifests(project_dir / "src" / "apps")
    generated_dir = project_dir / "src" / "core" / "generated"

    by_id = sorted(manifests, key=lambda item: item["persistent_id"])
    enum_rows = [f"    {item['id']} = {item['persistent_id']}," for item in by_id]
    ids_header = "\n".join(
        [
            "// Generated by tools/generate_app_catalog.py. Do not edit.",
            "#pragma once",
            "",
            "#include <stdint.h>",
            "",
            "enum class HostApp : uint8_t",
            "{",
            *enum_rows,
            "};",
            "",
        ]
    )

    includes = sorted({header for item in manifests for header in item["includes"]})
    includes_file = "\n".join(
        ["// Generated by tools/generate_app_catalog.py. Do not edit."]
        + [f'#include "{header}"' for header in includes]
        + [""]
    )

    catalog_rows = ["// Generated by tools/generate_app_catalog.py. Do not edit."]
    for item in sorted(manifests, key=lambda value: (value.get("order", 1000), value["persistent_id"])):
        callbacks = item["callbacks"]
        help_data = item["help"]
        options = item["options"]
        quick = item.get("quick_access")
        quick_value = (
            f"{{'{quick['key']}', {quick['open']}, {quick['available']}, {quick['active']}, {quick['close']}, {quick['input']}}}"
            if quick
            else "{0, nullptr, nullptr, nullptr, nullptr, nullptr}"
        )
        catalog_rows.extend(
            [
                "    {",
                f"        HostApp::{item['id']}, {json.dumps(item['name'])}, {json.dumps(item['header_tag'])},",
                f"        {callbacks['open']}, {callbacks['draw']}, {callbacks['input']}, {callbacks['tick']},",
                f"        {json.dumps(help_data['title'])}, {help_data['entries']}, {help_data['count']},",
                f"        {options['build']}, {str(options['enter_enabled']).lower()}, {str(options['show_run_hint']).lower()},",
                f"        {quick_value}",
                "    },",
            ]
        )
    catalog_rows.append("")

    write_if_changed(generated_dir / "AppIds.generated.h", ids_header)
    write_if_changed(generated_dir / "AppIncludes.generated.inc", includes_file)
    write_if_changed(generated_dir / "AppCatalog.generated.inc", "\n".join(catalog_rows))


try:
    Import("env")  # type: ignore[name-defined]  # noqa: F821
except NameError:
    if __name__ == "__main__":
        generate(Path(__file__).resolve().parents[1])
else:
    generate(Path(env.subst("$PROJECT_DIR")))  # type: ignore[name-defined]  # noqa: F821
